# Generated by Django 3.1.7 on 2021-03-27 19:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_card',
            field=wagtail.core.fields.StreamField([('testimonial_name', wagtail.core.blocks.CharBlock(form_classname='col12', required=True)), ('testimonial_message', wagtail.core.blocks.RichTextBlock(default='Paste clients message here...', form_classname='col12', required=True))], blank=True, null=True),
        ),
    ]
