# Generated by Django 3.1.7 on 2021-03-27 19:37

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonials_testimonial_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='testimonial_card',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_message',
            field=wagtail.core.fields.RichTextField(default='Paste message here...'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
