# Generated by Django 3.1.7 on 2021-03-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210325_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='form_blurb',
        ),
    ]
