# Generated by Django 3.1.7 on 2021-03-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_form_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='form_title',
            new_name='form_blurb',
        ),
    ]
