# Generated by Django 3.1.7 on 2021-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210322_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='home_page_panels',
            new_name='services_panels',
        ),
    ]
