# Generated by Django 3.1.7 on 2021-03-27 16:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('home', '0017_delete_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('testimonials_page_title', models.CharField(max_length=400, null=True)),
                ('testimonials_page_subtitle', wagtail.core.fields.RichTextField()),
                ('content', wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.StructBlock([('testimonial_name', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('testimonial_message', wagtail.core.blocks.RichTextBlock(max_length=214, required=True))]))], blank=True, null=True)),
                ('testimonials_page_background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
