# Generated by Django 3.1.7 on 2021-03-27 19:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20210327_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='testimonial_message',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='testimonial_name',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='content',
            field=wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.StructBlock([('testimonial_name', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('testimonial_message', wagtail.core.blocks.RichTextBlock(max_length=214, required=True))]))], blank=True, null=True),
        ),
    ]
