# Generated by Django 3.1.7 on 2021-03-22 20:25

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210322_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('service_cards', wagtail.core.blocks.StructBlock([('service_title', wagtail.core.blocks.CharBlock(help_text='Add Title', required=True)), ('service_cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('service_card_icon', wagtail.images.blocks.ImageChooserBlock()), ('service_title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('service_item', wagtail.core.blocks.RichTextBlock(max_length=75, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(help_text='Link to page on your website', required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='Link to EXTERNAL URL', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Button Text', max_length=45, required=True))]))], blank=True, null=True),
        ),
    ]
